#include "nvl/ui/Key.h"

#include <string>

#include "nvl/data/Map.h"

namespace nvl {

std::string Key::to_string() const {
    static const Map<Key::Value, std::string> names{
        {Key::Null, "Null"},
        {Key::Apostrophe, "'"},
        {Key::Comma, ","},
        {Key::Minus, "-"},
        {Key::Period, "."},
        {Key::Slash, "/"},
        {Key::Zero, "0"},
        {Key::One, "1"},
        {Key::Two, "2"},
        {Key::Three, "3"},
        {Key::Four, "4"},
        {Key::Five, "5"},
        {Key::Six, "6"},
        {Key::Seven, "7"},
        {Key::Eight, "8"},
        {Key::Nine, "9"},
        {Key::Semicolon, ";"},
        {Key::Equal, "="},
        {Key::A, "A"},
        {Key::B, "B"},
        {Key::C, "C"},
        {Key::D, "D"},
        {Key::E, "E"},
        {Key::F, "F"},
        {Key::G, "G"},
        {Key::H, "H"},
        {Key::I, "I"},
        {Key::J, "J"},
        {Key::K, "K"},
        {Key::L, "L"},
        {Key::M, "M"},
        {Key::N, "N"},
        {Key::O, "O"},
        {Key::P, "P"},
        {Key::Q, "Q"},
        {Key::R, "R"},
        {Key::S, "S"},
        {Key::T, "T"},
        {Key::U, "U"},
        {Key::V, "V"},
        {Key::W, "W"},
        {Key::X, "X"},
        {Key::Y, "Y"},
        {Key::Z, "Z"},
        {Key::LeftBracket, "["},
        {Key::Backslash, "\\"},
        {Key::RightBracket, "]"},
        {Key::Grave, "`"},
        {Key::Space, " "},
        {Key::Escape, "Esc"},
        {Key::Enter, "Enter"},
        {Key::Tab, "Tab"},
        {Key::Backspace, "Backspace"},
        {Key::Insert, "INS"},
        {Key::Delete, "DEL"},
        {Key::Right, "Right"},
        {Key::Left, "Left"},
        {Key::Down, "Down"},
        {Key::Up, "Up"},
        {Key::PageUp, "PageUp"},
        {Key::PageDown, "PageDown"},
        {Key::Home, "Home"},
        {Key::End, "End"},
        {Key::CapsLock, "CapsLock"},
        {Key::ScrollLock, "ScrollLock"},
        {Key::NumLock, "NumLock"},
        {Key::PrintScreen, "PrintScreen"},
        {Key::Pause, "Pause"},
        {Key::F1, "F1"},
        {Key::F2, "F2"},
        {Key::F3, "F3"},
        {Key::F4, "F4"},
        {Key::F5, "F5"},
        {Key::F6, "F6"},
        {Key::F7, "F7"},
        {Key::F8, "F8"},
        {Key::F9, "F9"},
        {Key::F10, "F10"},
        {Key::F11, "F11"},
        {Key::F12, "F12"},
        {Key::LeftShift, "LeftShift"},
        {Key::LeftCtrl, "LeftCtrl"},
        {Key::LeftAlt, "LeftAlt"},
        {Key::LeftSuper, "LeftSuper"},
        {Key::RightShift, "RightShift"},
        {Key::RightCtrl, "RightCtrl"},
        {Key::RightAlt, "RightAlt"},
        {Key::RightSuper, "RightSuper"},
        {Key::KB_MENU, "Menu"},

        {Key::KP_0, "Keypad0"},
        {Key::KP_1, "Keypad1"},
        {Key::KP_2, "Keypad2"},
        {Key::KP_3, "Keypad3"},
        {Key::KP_4, "Keypad4"},
        {Key::KP_5, "Keypad"},
        {Key::KP_6, "Keypad6"},
        {Key::KP_7, "Keypad7"},
        {Key::KP_8, "Keypad8"},
        {Key::KP_9, "Keypad9"},
        {Key::KP_Decimal, "Keypad."},
        {Key::KP_Divide, "Keypad/"},
        {Key::KP_Multiply, "Keypad*"},
        {Key::KP_Subtract, "Keypad-"},
        {Key::KP_Add, "Keypad+"},
        {Key::KP_Enter, "KeypadEnter"},
        {Key::KP_Equal, "Keypad="},
        {Key::Back, "Back"},
        {Key::Menu, "Menu"},
        {Key::VolumeUp, "VolumeUp"},
        {Key::VolumeDown, "VolumeDown"},
    };
    if (const auto iter = names.find(value); iter != names.end())
        return iter->second;
    return "Unknown (" + std::to_string(value) + ")";
}

} // namespace nvl