#include "nvl/ui/Key.h"

#include <string>

#include "nvl/data/Map.h"

namespace nvl {

std::string Key::to_string() const {
    static const Map<Value, std::string> names{
        {Null, "Null"},
        {Apostrophe, "'"},
        {Comma, ","},
        {Minus, "-"},
        {Period, "."},
        {Slash, "/"},
        {Zero, "0"},
        {One, "1"},
        {Two, "2"},
        {Three, "3"},
        {Four, "4"},
        {Five, "5"},
        {Six, "6"},
        {Seven, "7"},
        {Eight, "8"},
        {Nine, "9"},
        {Semicolon, ";"},
        {Equal, "="},
        {A, "A"},
        {B, "B"},
        {C, "C"},
        {D, "D"},
        {E, "E"},
        {F, "F"},
        {G, "G"},
        {H, "H"},
        {I, "I"},
        {J, "J"},
        {K, "K"},
        {L, "L"},
        {M, "M"},
        {N, "N"},
        {O, "O"},
        {P, "P"},
        {Q, "Q"},
        {R, "R"},
        {S, "S"},
        {T, "T"},
        {U, "U"},
        {V, "V"},
        {W, "W"},
        {X, "X"},
        {Y, "Y"},
        {Z, "Z"},
        {LeftBracket, "["},
        {Backslash, "\\"},
        {RightBracket, "]"},
        {Grave, "`"},
        {Space, " "},
        {Escape, "Esc"},
        {Enter, "Enter"},
        {Tab, "Tab"},
        {Backspace, "Backspace"},
        {Insert, "INS"},
        {Delete, "DEL"},
        {Right, "Right"},
        {Left, "Left"},
        {Down, "Down"},
        {Up, "Up"},
        {PageUp, "PageUp"},
        {PageDown, "PageDown"},
        {Home, "Home"},
        {End, "End"},
        {CapsLock, "CapsLock"},
        {ScrollLock, "ScrollLock"},
        {NumLock, "NumLock"},
        {PrintScreen, "PrintScreen"},
        {Pause, "Pause"},
        {F1, "F1"},
        {F2, "F2"},
        {F3, "F3"},
        {F4, "F4"},
        {F5, "F5"},
        {F6, "F6"},
        {F7, "F7"},
        {F8, "F8"},
        {F9, "F9"},
        {F10, "F10"},
        {F11, "F11"},
        {F12, "F12"},
        {LeftShift, "LeftShift"},
        {LeftCtrl, "LeftCtrl"},
        {LeftAlt, "LeftAlt"},
        {LeftSuper, "LeftSuper"},
        {RightShift, "RightShift"},
        {RightCtrl, "RightCtrl"},
        {RightAlt, "RightAlt"},
        {RightSuper, "RightSuper"},
        {KB_MENU, "Menu"},

        {KP_0, "Keypad0"},
        {KP_1, "Keypad1"},
        {KP_2, "Keypad2"},
        {KP_3, "Keypad3"},
        {KP_4, "Keypad4"},
        {KP_5, "Keypad"},
        {KP_6, "Keypad6"},
        {KP_7, "Keypad7"},
        {KP_8, "Keypad8"},
        {KP_9, "Keypad9"},
        {KP_Decimal, "Keypad."},
        {KP_Divide, "Keypad/"},
        {KP_Multiply, "Keypad*"},
        {KP_Subtract, "Keypad-"},
        {KP_Add, "Keypad+"},
        {KP_Enter, "KeypadEnter"},
        {KP_Equal, "Keypad="},
        {Back, "Back"},
        {Menu, "Menu"},
        {VolumeUp, "VolumeUp"},
        {VolumeDown, "VolumeDown"},
    };
    if (const auto iter = names.find(value); iter != names.end())
        return iter->second;
    return "Unknown (" + std::to_string(value) + ")";
}

} // namespace nvl